from resources.auth_resource import auth_blueprint
from resources.admin_resource import admin_blueprint
from resources.company_resource import company_blueprint
from resources.student_resource import student_blueprint